import ProductsGrid from "./ProductsGrid";

import Pink from "@/public/assets/images/pink_bag.png";
import Yellow from "@/public/assets/images/yellow_bag.png";
import Black from "@/public/assets/images/black_bag.png";
import Brown from "@/public/assets/images/brown_bag.png";
import Heart from "@/components/icons/Heart";

const CategoryComponent = () => {
    const products = [
        {
            id: 1,
            title: "Grande",
            icon: Heart.src,
            subTitle: "Blossom Pouch",
            price: 39.49,
            offPrice: 78.66,
            offPercent: "50% OFF",
            image: Pink.src,
            route: "/",
        },
        {
            id: 2,
            title: "Remus",
            icon: Heart.src,
            subTitle: "Brown Strap Bag",
            price: 57.0,
            offPrice: 78.66,
            offPercent: "50% OFF",
            image: Brown.src,
            route: "/",
        },

        {
            id: 3,
            title: "Coach",
            icon: Heart.src,
            subTitle: "Leather Coach Bag",
            price: 54.69,
            offPrice: 78.66,
            offPercent: "50% OFF",
            image: Yellow.src,
            route: "/",
        },

        {
            id: 4,
            title: "Boujee",
            icon: Heart.src,
            subTitle: "Black Bag",
            price: 56.49,
            offPrice: 78.66,
            offPercent: "50% OFF",
            image: Black.src,
            route: "/",
        },
        {
            id: 5,
            title: "Grande",
            icon: Heart.src,
            subTitle: "Blossom Pouch",
            price: 39.49,
            offPrice: 78.66,
            offPercent: "50% OFF",
            image: Pink.src,
            route: "/",
        },
        {
            id: 6,
            title: "Grande",
            icon: Heart.src,
            subTitle: "Blossom Pouch",
            price: 39.49,
            offPrice: 78.66,
            offPercent: "50% OFF",
            image: Pink.src,
            route: "/",
        },
        {
            id: 7,
            title: "Grande",
            icon: Heart.src,
            subTitle: "Blossom Pouch",
            price: 39.49,
            offPrice: 78.66,
            offPercent: "50% OFF",
            image: Pink.src,
            route: "/",
        },
        {
            id: 8,
            title: "Grande",
            icon: Heart.src,
            subTitle: "Blossom Pouch",
            price: 39.49,
            offPrice: 78.66,
            offPercent: "50% OFF",
            image: Pink.src,
            route: "/",
        },
        {
            id: 9,
            title: "Grande",
            icon: Heart.src,
            subTitle: "Blossom Pouch",
            price: 39.49,
            offPrice: 78.66,
            offPercent: "50% OFF",
            image: Pink.src,
            route: "/",
        },
        {
            id: 10,
            title: "Grande",
            icon: Heart.src,
            subTitle: "Blossom Pouch",
            price: 39.49,
            offPrice: 78.66,
            offPercent: "50% OFF",
            image: Pink.src,
            route: "/",
        },
        {
            id: 11,
            title: "Remus",
            icon: Heart.src,
            subTitle: "Brown Strap Bag",
            price: 57.0,
            offPrice: 78.66,
            offPercent: "50% OFF",
            image: Brown.src,
            route: "/",
        },

        {
            id: 12,
            title: "Coach",
            icon: Heart.src,
            subTitle: "Leather Coach Bag",
            price: 54.69,
            offPrice: 78.66,
            offPercent: "50% OFF",
            image: Yellow.src,
            route: "/",
        },

        {
            id: 13,
            title: "Boujee",
            icon: Heart.src,
            subTitle: "Black Bag",
            price: 56.49,
            offPrice: 78.66,
            offPercent: "50% OFF",
            image: Black.src,
            route: "/",
        },
        {
            id: 14,
            title: "Grande",
            icon: Heart.src,
            subTitle: "Blossom Pouch",
            price: 39.49,
            offPrice: 78.66,
            offPercent: "50% OFF",
            image: Pink.src,
            route: "/",
        },
        {
            id: 15,
            title: "Grande",
            icon: Heart.src,
            subTitle: "Blossom Pouch",
            price: 39.49,
            offPrice: 78.66,
            offPercent: "50% OFF",
            image: Pink.src,
            route: "/",
        },
        {
            id: 16,
            title: "Grande",
            icon: Heart.src,
            subTitle: "Blossom Pouch",
            price: 39.49,
            offPrice: 78.66,
            offPercent: "50% OFF",
            image: Pink.src,
            route: "/",
        },
        {
            id: 17,
            title: "Grande",
            icon: Heart.src,
            subTitle: "Blossom Pouch",
            price: 39.49,
            offPrice: 78.66,
            offPercent: "50% OFF",
            image: Pink.src,
            route: "/",
        },
        {
            id: 18,
            title: "Grande",
            icon: Heart.src,
            subTitle: "Blossom Pouch",
            price: 39.49,
            offPrice: 78.66,
            offPercent: "50% OFF",
            image: Pink.src,
            route: "/",
        },
        {
            id: 19,
            title: "Grande",
            icon: Heart.src,
            subTitle: "Blossom Pouch",
            price: 39.49,
            offPrice: 78.66,
            offPercent: "50% OFF",
            image: Pink.src,
            route: "/",
        },
        {
            id: 20,
            title: "Remus",
            icon: Heart.src,
            subTitle: "Brown Strap Bag",
            price: 57.0,
            offPrice: 78.66,
            offPercent: "50% OFF",
            image: Brown.src,
            route: "/",
        },

        {
            id: 21,
            title: "Coach",
            icon: Heart.src,
            subTitle: "Leather Coach Bag",
            price: 54.69,
            offPrice: 78.66,
            offPercent: "50% OFF",
            image: Yellow.src,
            route: "/",
        },

        {
            id: 22,
            title: "Boujee",
            icon: Heart.src,
            subTitle: "Black Bag",
            price: 56.49,
            offPrice: 78.66,
            offPercent: "50% OFF",
            image: Black.src,
            route: "/",
        },
        {
            id: 23,
            title: "Grande",
            icon: Heart.src,
            subTitle: "Blossom Pouch",
            price: 39.49,
            offPrice: 78.66,
            offPercent: "50% OFF",
            image: Pink.src,
            route: "/",
        },
        {
            id: 24,
            title: "Grande",
            icon: Heart.src,
            subTitle: "Blossom Pouch",
            price: 39.49,
            offPrice: 78.66,
            offPercent: "50% OFF",
            image: Pink.src,
            route: "/",
        },
        {
            id: 25,
            title: "Grande",
            icon: Heart.src,
            subTitle: "Blossom Pouch",
            price: 39.49,
            offPrice: 78.66,
            offPercent: "50% OFF",
            image: Pink.src,
            route: "/",
        },
        {
            id: 26,
            title: "Grande",
            icon: Heart.src,
            subTitle: "Blossom Pouch",
            price: 39.49,
            offPrice: 78.66,
            offPercent: "50% OFF",
            image: Pink.src,
            route: "/",
        },
        {
            id: 27,
            title: "Grande",
            icon: Heart.src,
            subTitle: "Blossom Pouch",
            price: 39.49,
            offPrice: 78.66,
            offPercent: "50% OFF",
            image: Pink.src,
            route: "/",
        },
        {
            id: 28,
            title: "Grande",
            icon: Heart.src,
            subTitle: "Blossom Pouch",
            price: 39.49,
            offPrice: 78.66,
            offPercent: "50% OFF",
            image: Pink.src,
            route: "/",
        },
        {
            id: 29,
            title: "Remus",
            icon: Heart.src,
            subTitle: "Brown Strap Bag",
            price: 57.0,
            offPrice: 78.66,
            offPercent: "50% OFF",
            image: Brown.src,
            route: "/",
        },

        {
            id: 30,
            title: "Coach",
            icon: Heart.src,
            subTitle: "Leather Coach Bag",
            price: 54.69,
            offPrice: 78.66,
            offPercent: "50% OFF",
            image: Yellow.src,
            route: "/",
        },

        {
            id: 31,
            title: "Boujee",
            icon: Heart.src,
            subTitle: "Black Bag",
            price: 56.49,
            offPrice: 78.66,
            offPercent: "50% OFF",
            image: Black.src,
            route: "/",
        },
        {
            id: 32,
            title: "Grande",
            icon: Heart.src,
            subTitle: "Blossom Pouch",
            price: 39.49,
            offPrice: 78.66,
            offPercent: "50% OFF",
            image: Pink.src,
            route: "/",
        },
        {
            id: 33,
            title: "Grande",
            icon: Heart.src,
            subTitle: "Blossom Pouch",
            price: 39.49,
            offPrice: 78.66,
            offPercent: "50% OFF",
            image: Pink.src,
            route: "/",
        },
        {
            id: 34,
            title: "Grande",
            icon: Heart.src,
            subTitle: "Blossom Pouch",
            price: 39.49,
            offPrice: 78.66,
            offPercent: "50% OFF",
            image: Pink.src,
            route: "/",
        },
        {
            id: 35,
            title: "Grande",
            icon: Heart.src,
            subTitle: "Blossom Pouch",
            price: 39.49,
            offPrice: 78.66,
            offPercent: "50% OFF",
            image: Pink.src,
            route: "/",
        },
        {
            id: 36,
            title: "Grande",
            icon: Heart.src,
            subTitle: "Blossom Pouch",
            price: 39.49,
            offPrice: 78.66,
            offPercent: "50% OFF",
            image: Pink.src,
            route: "/",
        },
        {
            id: 37,
            title: "Grande",
            icon: Heart.src,
            subTitle: "Blossom Pouch",
            price: 39.49,
            offPrice: 78.66,
            offPercent: "50% OFF",
            image: Pink.src,
            route: "/",
        },
        {
            id: 38,
            title: "Remus",
            icon: Heart.src,
            subTitle: "Brown Strap Bag",
            price: 57.0,
            offPrice: 78.66,
            offPercent: "50% OFF",
            image: Brown.src,
            route: "/",
        },

        {
            id: 39,
            title: "Coach",
            icon: Heart.src,
            subTitle: "Leather Coach Bag",
            price: 54.69,
            offPrice: 78.66,
            offPercent: "50% OFF",
            image: Yellow.src,
            route: "/",
        },

        {
            id: 40,
            title: "Boujee",
            icon: Heart.src,
            subTitle: "Black Bag",
            price: 56.49,
            offPrice: 78.66,
            offPercent: "50% OFF",
            image: Black.src,
            route: "/",
        },
        {
            id: 41,
            title: "Grande",
            icon: Heart.src,
            subTitle: "Blossom Pouch",
            price: 39.49,
            offPrice: 78.66,
            offPercent: "50% OFF",
            image: Pink.src,
            route: "/",
        },
        {
            id: 42,
            title: "Grande",
            icon: Heart.src,
            subTitle: "Blossom Pouch",
            price: 39.49,
            offPrice: 78.66,
            offPercent: "50% OFF",
            image: Pink.src,
            route: "/",
        },
        {
            id: 43,
            title: "Grande",
            icon: Heart.src,
            subTitle: "Blossom Pouch",
            price: 39.49,
            offPrice: 78.66,
            offPercent: "50% OFF",
            image: Pink.src,
            route: "/",
        },
        {
            id: 44,
            title: "Grande",
            icon: Heart.src,
            subTitle: "Blossom Pouch",
            price: 39.49,
            offPrice: 78.66,
            offPercent: "50% OFF",
            image: Pink.src,
            route: "/",
        },
        {
            id: 45,
            title: "Grande",
            icon: Heart.src,
            subTitle: "Blossom Pouch",
            price: 39.49,
            offPrice: 78.66,
            offPercent: "60% OFF",
            image: Pink.src,
            route: "/",
        },
    ];

    return (
        <>
            <ProductsGrid products={products} />
        </>
    );
};

export default CategoryComponent;
